name: C2

# Menjalankan secara otomatis setiap 4 jam
on:
  schedule:
    - cron: '0 */6 * * *'  # Setiap 6 jam pada menit ke-0

jobs:
  update-repo:
    runs-on: ubuntu-latest  # Menjalankan job di lingkungan Ubuntu
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Mengambil kode dari repository

      - name: Setup GPG key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --import --batch --yes  # Mengimpor GPG key dari secret
          gpg --list-secret-keys  # Menampilkan kunci rahasia untuk verifikasi

      - name: Configure Git
        run: |
          git config user.name "ducky"  # Mengatur nama pengguna untuk commit
          git config user.email "dedukwijaya@gmail.com"  # Mengatur email pengguna untuk commit
          git config user.signingkey F77FA5C7E92588A756B36E606FD5D53407B2C619  # Menambahkan GPG key ID
          git config commit.gpgsign true

      - name: Update README, commit, dan push
        run: |
          export TZ="Asia/Jakarta"  # Mengatur zona waktu ke Asia/Jakarta (WIB)
          TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S %Z")  # Mendapatkan timestamp dalam format yang diinginkan (WIB)
          echo "Last updated: $TIMESTAMP" > README.md  # Perbarui README.md dengan timestamp WIB
          git add README.md  # Menambahkan README.md ke staging area
          git commit -S -m "Auto update README at $TIMESTAMP" || echo "No changes to commit"  # Commit dengan tanda tangan
          git push origin main  # Mengirimkan perubahan ke branch 'main'
